[tool.black]
line_length = 100
target_version = ["py310"]
exclude = "(venv), (migrations), settings.py, manage.py"

[tool.isort]
profile = "black"
combine_as_imports = true
include_trailing_comma = true
line_length = 100
multi_line_output = 3
reverse_relative = true
use_parentheses = true
